// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: product_service.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace gRPC_Client.protos {
  public static partial class ProductService
  {
    static readonly string __ServiceName = "ProductService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::gRPC_Client.protos.CreateProductRequestDto> __Marshaller_CreateProductRequestDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::gRPC_Client.protos.CreateProductRequestDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::gRPC_Client.protos.CreateProductResponseDto> __Marshaller_CreateProductResponseDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::gRPC_Client.protos.CreateProductResponseDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::gRPC_Client.protos.GetProductByTagRequestDto> __Marshaller_GetProductByTagRequestDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::gRPC_Client.protos.GetProductByTagRequestDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::gRPC_Client.protos.GetProductByTagResponseDto> __Marshaller_GetProductByTagResponseDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::gRPC_Client.protos.GetProductByTagResponseDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::gRPC_Client.protos.UpdateProductRequestDto> __Marshaller_UpdateProductRequestDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::gRPC_Client.protos.UpdateProductRequestDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::gRPC_Client.protos.UpdateProductResponseDto> __Marshaller_UpdateProductResponseDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::gRPC_Client.protos.UpdateProductResponseDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::gRPC_Client.protos.GetProductByIdRequestDto> __Marshaller_GetProductByIdRequestDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::gRPC_Client.protos.GetProductByIdRequestDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::gRPC_Client.protos.GetProductByIdResponseDto> __Marshaller_GetProductByIdResponseDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::gRPC_Client.protos.GetProductByIdResponseDto.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::gRPC_Client.protos.CreateProductRequestDto, global::gRPC_Client.protos.CreateProductResponseDto> __Method_CreateProduct = new grpc::Method<global::gRPC_Client.protos.CreateProductRequestDto, global::gRPC_Client.protos.CreateProductResponseDto>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateProduct",
        __Marshaller_CreateProductRequestDto,
        __Marshaller_CreateProductResponseDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::gRPC_Client.protos.GetProductByTagRequestDto, global::gRPC_Client.protos.GetProductByTagResponseDto> __Method_GetProductByTag = new grpc::Method<global::gRPC_Client.protos.GetProductByTagRequestDto, global::gRPC_Client.protos.GetProductByTagResponseDto>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetProductByTag",
        __Marshaller_GetProductByTagRequestDto,
        __Marshaller_GetProductByTagResponseDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::gRPC_Client.protos.UpdateProductRequestDto, global::gRPC_Client.protos.UpdateProductResponseDto> __Method_UpdateProduct = new grpc::Method<global::gRPC_Client.protos.UpdateProductRequestDto, global::gRPC_Client.protos.UpdateProductResponseDto>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "UpdateProduct",
        __Marshaller_UpdateProductRequestDto,
        __Marshaller_UpdateProductResponseDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::gRPC_Client.protos.GetProductByIdRequestDto, global::gRPC_Client.protos.GetProductByIdResponseDto> __Method_GetProducyById = new grpc::Method<global::gRPC_Client.protos.GetProductByIdRequestDto, global::gRPC_Client.protos.GetProductByIdResponseDto>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "GetProducyById",
        __Marshaller_GetProductByIdRequestDto,
        __Marshaller_GetProductByIdResponseDto);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::gRPC_Client.protos.ProductServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ProductService</summary>
    [grpc::BindServiceMethod(typeof(ProductService), "BindService")]
    public abstract partial class ProductServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::gRPC_Client.protos.CreateProductResponseDto> CreateProduct(global::gRPC_Client.protos.CreateProductRequestDto request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task GetProductByTag(global::gRPC_Client.protos.GetProductByTagRequestDto request, grpc::IServerStreamWriter<global::gRPC_Client.protos.GetProductByTagResponseDto> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::gRPC_Client.protos.UpdateProductResponseDto> UpdateProduct(grpc::IAsyncStreamReader<global::gRPC_Client.protos.UpdateProductRequestDto> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task GetProducyById(grpc::IAsyncStreamReader<global::gRPC_Client.protos.GetProductByIdRequestDto> requestStream, grpc::IServerStreamWriter<global::gRPC_Client.protos.GetProductByIdResponseDto> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ProductService</summary>
    public partial class ProductServiceClient : grpc::ClientBase<ProductServiceClient>
    {
      /// <summary>Creates a new client for ProductService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ProductServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ProductService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ProductServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ProductServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ProductServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::gRPC_Client.protos.CreateProductResponseDto CreateProduct(global::gRPC_Client.protos.CreateProductRequestDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateProduct(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::gRPC_Client.protos.CreateProductResponseDto CreateProduct(global::gRPC_Client.protos.CreateProductRequestDto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateProduct, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::gRPC_Client.protos.CreateProductResponseDto> CreateProductAsync(global::gRPC_Client.protos.CreateProductRequestDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateProductAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::gRPC_Client.protos.CreateProductResponseDto> CreateProductAsync(global::gRPC_Client.protos.CreateProductRequestDto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateProduct, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::gRPC_Client.protos.GetProductByTagResponseDto> GetProductByTag(global::gRPC_Client.protos.GetProductByTagRequestDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetProductByTag(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::gRPC_Client.protos.GetProductByTagResponseDto> GetProductByTag(global::gRPC_Client.protos.GetProductByTagRequestDto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetProductByTag, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::gRPC_Client.protos.UpdateProductRequestDto, global::gRPC_Client.protos.UpdateProductResponseDto> UpdateProduct(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateProduct(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::gRPC_Client.protos.UpdateProductRequestDto, global::gRPC_Client.protos.UpdateProductResponseDto> UpdateProduct(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_UpdateProduct, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::gRPC_Client.protos.GetProductByIdRequestDto, global::gRPC_Client.protos.GetProductByIdResponseDto> GetProducyById(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetProducyById(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::gRPC_Client.protos.GetProductByIdRequestDto, global::gRPC_Client.protos.GetProductByIdResponseDto> GetProducyById(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_GetProducyById, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ProductServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ProductServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(ProductServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateProduct, serviceImpl.CreateProduct)
          .AddMethod(__Method_GetProductByTag, serviceImpl.GetProductByTag)
          .AddMethod(__Method_UpdateProduct, serviceImpl.UpdateProduct)
          .AddMethod(__Method_GetProducyById, serviceImpl.GetProducyById).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ProductServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateProduct, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::gRPC_Client.protos.CreateProductRequestDto, global::gRPC_Client.protos.CreateProductResponseDto>(serviceImpl.CreateProduct));
      serviceBinder.AddMethod(__Method_GetProductByTag, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::gRPC_Client.protos.GetProductByTagRequestDto, global::gRPC_Client.protos.GetProductByTagResponseDto>(serviceImpl.GetProductByTag));
      serviceBinder.AddMethod(__Method_UpdateProduct, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::gRPC_Client.protos.UpdateProductRequestDto, global::gRPC_Client.protos.UpdateProductResponseDto>(serviceImpl.UpdateProduct));
      serviceBinder.AddMethod(__Method_GetProducyById, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::gRPC_Client.protos.GetProductByIdRequestDto, global::gRPC_Client.protos.GetProductByIdResponseDto>(serviceImpl.GetProducyById));
    }

  }
}
#endregion
